
import React from 'react';

interface ImagePanelProps {
  imageUrl: string | null;
  isLoading: boolean;
  error: string | null;
}

const LoadingSpinner: React.FC = () => (
  <div className="flex flex-col items-center justify-center text-center gap-4">
    <div className="w-16 h-16 border-4 border-dashed rounded-full animate-spin border-indigo-400"></div>
    <p className="text-slate-400 font-medium">Generating your vision...</p>
    <p className="text-slate-500 text-sm">This can take a moment. Great art requires patience!</p>
  </div>
);

const Placeholder: React.FC = () => (
    <div className="flex flex-col items-center justify-center text-center text-slate-500 gap-4">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-24 w-24 opacity-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
        <h3 className="text-xl font-semibold text-slate-400">AI Image Generation</h3>
        <p className="max-w-sm">Use the chat on the left to describe an image. Your generated masterpiece will appear here.</p>
    </div>
);

const ErrorDisplay: React.FC<{ message: string }> = ({ message }) => (
    <div className="flex flex-col items-center justify-center text-center text-red-400 bg-red-900/20 p-8 rounded-lg">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <h3 className="text-lg font-bold">Generation Failed</h3>
        <p className="text-red-300">{message}</p>
    </div>
);


const ImagePanel: React.FC<ImagePanelProps> = ({ imageUrl, isLoading, error }) => {
  return (
    <div className="flex items-center justify-center h-full p-8 bg-slate-900">
      <div className="w-full h-full max-w-3xl max-h-[80vh] flex items-center justify-center">
        {isLoading && <LoadingSpinner />}
        {!isLoading && error && <ErrorDisplay message={error} />}
        {!isLoading && !error && imageUrl && (
          <img
            src={imageUrl}
            alt="Generated by AI"
            className="object-contain w-full h-full rounded-lg shadow-2xl shadow-indigo-900/50"
          />
        )}
        {!isLoading && !error && !imageUrl && <Placeholder />}
      </div>
    </div>
  );
};

export default ImagePanel;
